name: beetrap
version: '1.1'
main: edu.rochester.beetrap.Main
api-version: '1.20'
commands:
  draw_quad:
    description: Draws a quad with glass blocks
    usage: /<command> <xCenter> <yCenter> <zCenter> <sideLengthToCenter>
  garden:
    description: Manage gardens
    usage: /<command> <create|destroy|list>
  game:
    description: create an instance of Beetrap Minecraft
    usage: /<command> <new|destroy>
  bee:
    description: Spawns a bee saying things
    usage: /<command> <things>
  beed:
    description: Set the dialogue of the unique bee
    usage: /<command> <things>
  beeds:
    description: Set a sequence of dialogues of the unique bee for him to speak
    usage: /<command> <phrase1> | <phrase2> | ...